project_id = "xkmthvuvfscqqkiqkayy"

[functions.sentiment-analysis]
verify_jwt = false

[functions.monetary-intelligence]
verify_jwt = false

[functions.topic-analysis]
verify_jwt = false

[functions.counterfactual]
verify_jwt = false
