// ── Sentiment Analysis — Full (POST-based, no req.url access) ──
// CRITICAL: Do NOT access req.url — it crashes this edge runtime.
// Use POST with JSON body for parameters instead.
const CH = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};
const HW = ['rate hike','tightening','hawkish','restrictive','overheating','persistent inflation','price pressures','strong demand','upside risks to inflation','insufficiently restrictive','further tightening'];
const DW = ['rate cut','easing','dovish','accommodative','disinflation','slowing','weaker growth','downside risks','disinflationary','progress on inflation','cutting rates','lower rates','policy pivot','sufficiently restrictive'];
const DP: Record<string,{h:string[];d:string[]}> = {
  'wage growth':{h:['accelerat','rising','elevated','strong','above'],d:['moderat','eased','easing','slowing','soften','deceler']},
  'inflation':{h:['above target','persistently','sticky','broad-based','accelerat'],d:['falling','declining','easing','retreating','moderat','lower','disinflation']},
  'growth':{h:['robust','strong','solid','resilient','accelerat'],d:['slowing','contract','recession','weak','stagnant','deteriorat']},
  'unemployment':{h:['historic low','tight','below natural','record low'],d:['rising','elevated','increasing','higher','deteriorat']},
};
interface It{bank:string;source:string;item_date:string;title:string;url:string;is_statistical:boolean;hawk_pts:number;dove_pts:number;net_score:number;label:string;word_count:number;reasons:string[];stat_metric:string|null;stat_value:number|null;stat_weight:number;}
function sc(text:string,title=''){const c=(title+' '+text).toLowerCase();let hp=0,dp=0;const rs:string[]=[];for(const w of HW)if(c.includes(w)){hp++;rs.push('h:'+w);}for(const w of DW)if(c.includes(w)){dp++;rs.push('d:'+w);}for(const[p,m]of Object.entries(DP)){let i=c.indexOf(p);while(i!==-1){const ctx=c.slice(Math.max(0,i-120),Math.min(c.length,i+p.length+120));const hh=m.h.some(x=>ctx.includes(x)),dd=m.d.some(x=>ctx.includes(x));if(hh&&!dd){hp+=5;rs.push('dh:'+p);}else if(dd&&!hh){dp+=5;rs.push('dd:'+p);}i=c.indexOf(p,i+1);}}const wc=Math.max(c.split(/\s+/).length,1);const net=((hp-dp)/wc)*100;return{hawk_pts:hp,dove_pts:dp,net_score:Math.round(net*1000)/1000,label:net>0.05?'hawkish':net<-0.05?'dovish':'neutral',word_count:wc,reasons:rs};}
function sv(v:number,ht:number,dt:number,dir:string,w:number,met:string){let raw:number,lb:string;const B=0.15;if(dir==='lh'){if(v<=ht){raw=Math.max(Math.min((ht-v)/Math.max(Math.abs(ht),1)*2,2),B);lb='hawkish';}else if(v>=dt){raw=-Math.max(Math.min((v-dt)/Math.max(Math.abs(dt),1)*2,2),B);lb='dovish';}else{raw=-(v-(ht+dt)/2)/Math.max(Math.abs(ht-dt),1);lb=raw>0.05?'hawkish':raw<-0.05?'dovish':'neutral';}}else{if(v>=ht){raw=Math.max(Math.min((v-ht)/Math.max(Math.abs(ht),1)*2,2),B);lb='hawkish';}else if(v<=dt){raw=-Math.max(Math.min(Math.abs(dt-v)/Math.max(Math.abs(dt),1)*2,2),B);lb='dovish';}else{raw=(v-(ht+dt)/2)/Math.max(Math.abs(ht-dt),1);lb=raw>0.05?'hawkish':raw<-0.05?'dovish':'neutral';}}return{net_score:Math.round(raw*w*1000)/1000,label:lb,metric:met,value:Math.round(v*100)/100};}
const UA='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36';
async function sf(url:string,ms=12000):Promise<Response|null>{try{const ac=new AbortController();const t=setTimeout(()=>ac.abort(),ms);const r=await fetch(url,{headers:{'User-Agent':UA},signal:ac.signal});clearTimeout(t);return r;}catch{return null;}}
function cd(xml:string,tag:string):string{const m=xml.match(new RegExp('<'+tag+'[^>]*>\\s*(?:<!\\[CDATA\\[)?([\\s\\S]*?)(?:\\]\\]>)?\\s*</'+tag+'>','i'));return m?m[1].trim():'';}
function pi(xml:string){const items:{title:string;link:string;pubDate:string;cat:string}[]=[];const re=new RegExp('<item>([\\s\\S]*?)</item>','gi');let m;while((m=re.exec(xml))!==null)items.push({title:cd(m[1],'title'),link:cd(m[1],'link')||cd(m[1],'guid'),pubDate:cd(m[1],'pubDate'),cat:cd(m[1],'category').toLowerCase()});return items;}
function ae(xml:string){const entries:{title:string;link:string;updated:string}[]=[];const re=new RegExp('<entry>([\\s\\S]*?)</entry>','gi');let m;while((m=re.exec(xml))!==null){const lm=m[1].match(new RegExp('<link[^>]+href=["\']([^"\']+)["\']','i'));entries.push({title:cd(m[1],'title'),link:lm?lm[1].trim():'',updated:cd(m[1],'updated')});}return entries;}
function td(t:string):string|null{if(!t)return null;try{const d=new Date(t);return isNaN(d.getTime())?null:d.toISOString().split('T')[0];}catch{return null;}}
function xn(title:string):number|null{const m=title.toLowerCase().match(new RegExp('(-?\\d+\\.?\\d*)\\s*%'));if(!m)return null;const v=parseFloat(m[1]);return isNaN(v)?null:v;}
// FRED
interface FS{id:string;met:string;tr:string;ht:number;dt:number;dir:string;w:number}
const FR:FS[]=[{id:'CPIAUCSL',met:'CPI YoY',tr:'p12',ht:3,dt:2,dir:'hh',w:3},{id:'PAYEMS',met:'Payrolls MoM',tr:'d1',ht:200,dt:100,dir:'hh',w:3},{id:'UNRATE',met:'Unemployment',tr:'lv',ht:4,dt:5,dir:'lh',w:3},{id:'PCEPILFE',met:'Core PCE YoY',tr:'p12',ht:2.5,dt:2,dir:'hh',w:3},{id:'FEDFUNDS',met:'Fed Funds',tr:'lv',ht:5,dt:3,dir:'hh',w:1},{id:'RSAFS',met:'Retail Sales',tr:'p1',ht:0.5,dt:-0.2,dir:'hh',w:2},{id:'INDPRO',met:'Ind Prod',tr:'p1',ht:0.3,dt:-0.3,dir:'hh',w:2}];
async function fetchFred(key:string,days:number):Promise<It[]>{const co=new Date();co.setDate(co.getDate()-days);const cs=co.toISOString().split('T')[0];const res=await Promise.allSettled(FR.map(async s=>{const r=await sf('https://api.stlouisfed.org/fred/series/observations?series_id='+s.id+'&api_key='+key+'&file_type=json&sort_order=desc&limit=15');if(!r||!r.ok)return null;const d=await r.json();const obs=(d.observations||[]).filter((o:any)=>o.value!=='.');if(!obs.length||obs[0].date<cs)return null;const v=obs.map((o:any)=>parseFloat(o.value));let val:number|null=null;if(s.tr==='lv')val=v[0];else if(s.tr==='d1'&&v.length>=2)val=v[0]-v[1];else if(s.tr==='p1'&&v.length>=2&&v[1]!==0)val=((v[0]-v[1])/Math.abs(v[1]))*100;else if(s.tr==='p12'&&v.length>=13&&v[12]!==0)val=((v[0]-v[12])/Math.abs(v[12]))*100;if(val===null)return null;const r2=sv(val,s.ht,s.dt,s.dir,s.w,s.met);return{bank:'FED',source:'FRED',item_date:obs[0].date,title:s.met+': '+val.toFixed(2)+' ('+s.id+')',url:'https://fred.stlouisfed.org/series/'+s.id,is_statistical:true,hawk_pts:0,dove_pts:0,net_score:r2.net_score,label:r2.label,word_count:0,reasons:['fred'],stat_metric:r2.metric,stat_value:r2.value,stat_weight:s.w}as It;}));return res.filter(r=>r.status==='fulfilled'&&r.value).map(r=>(r as PromiseFulfilledResult<It>).value);}
// RSS feeds
const SKIP=new Set(['enforcement actions','orders on banking applications','other announcements','banking and consumer regulatory policy','community development']);
async function fetchRss(cs:string,bank:string):Promise<It[]>{const items:It[]=[];const feeds=bank==='FED'?[{url:'https://www.federalreserve.gov/feeds/speeches.xml',lbl:'Fed Speech'},{url:'https://www.federalreserve.gov/feeds/press_monetary.xml',lbl:'Fed Monetary'},{url:'https://www.federalreserve.gov/feeds/press_all.xml',lbl:'Fed Press'}]:[{url:'https://www.ecb.europa.eu/rss/press.html',lbl:'ECB Press'},{url:'https://www.ecb.europa.eu/rss/blog.html',lbl:'ECB Blog'}];const res=await Promise.allSettled(feeds.map(async f=>{const r=await sf(f.url);if(!r||!r.ok)return[];let xml=await r.text();xml=xml.replace(new RegExp('&(?!amp;|lt;|gt;|quot;|apos;|#)','g'),'&amp;');return pi(xml).filter(ri=>{const p=td(ri.pubDate);if(!p||p<cs)return false;if(f.lbl==='Fed Press'&&SKIP.has(ri.cat))return false;return true;}).slice(0,15).map(ri=>{const pub=td(ri.pubDate)!;const s=sc('',ri.title);return{bank,source:f.lbl,item_date:pub,title:ri.title,url:ri.link,is_statistical:false,...s,stat_metric:null,stat_value:null,stat_weight:0}as It;});}));for(const r of res)if(r.status==='fulfilled')items.push(...r.value);return items;}
// ECB Stats + Eurostat
interface SR{pattern:string;met:string;ht:number|null;dt:number|null;dir:string;w:number}
const EU:SR[]=[{pattern:'inflation',met:'HICP',ht:2.5,dt:1.8,dir:'hh',w:3},{pattern:'gdp',met:'GDP',ht:0.4,dt:0.1,dir:'hh',w:3},{pattern:'unemployment',met:'Unemployment',ht:6,dt:7.5,dir:'lh',w:3},{pattern:'industrial production',met:'Ind Prod',ht:0.5,dt:-0.5,dir:'hh',w:2},{pattern:'producer prices',met:'PPI',ht:0.5,dt:-0.3,dir:'hh',w:2}];
function ss(title:string):{ns:number;lb:string;met:string;val:number|null;w:number}|null{const tl=title.toLowerCase();for(const r of EU){if(!tl.includes(r.pattern))continue;const v=xn(title);if(v!==null&&r.ht!==null&&r.dt!==null){const s=sv(v,r.ht,r.dt,r.dir,r.w,r.met);return{ns:s.net_score,lb:s.label,met:s.metric,val:s.value,w:r.w};}break;}return null;}
async function fetchEcbStats(cs:string):Promise<It[]>{const items:It[]=[];try{const r=await sf('https://www.ecb.europa.eu/rss/statpress.html');if(r&&r.ok){let xml=await r.text();xml=xml.replace(new RegExp('&(?!amp;|lt;|gt;|quot;|apos;|#)','g'),'&amp;');for(const ri of pi(xml).filter(ri=>{const p=td(ri.pubDate);return p&&p>=cs;}).slice(0,15)){const pub=td(ri.pubDate)!;const st=ss(ri.title);if(st)items.push({bank:'ECB',source:'ECB Stats',item_date:pub,title:ri.title,url:ri.link,is_statistical:true,hawk_pts:0,dove_pts:0,net_score:st.ns,label:st.lb,word_count:0,reasons:['numeric'],stat_metric:st.met,stat_value:st.val,stat_weight:st.w});else items.push({bank:'ECB',source:'ECB Stats',item_date:pub,title:ri.title,url:ri.link,is_statistical:true,hawk_pts:0,dove_pts:0,net_score:0,label:'neutral',word_count:0,reasons:[],stat_metric:null,stat_value:null,stat_weight:0});}}}catch(e){console.error('ECB stats:',e);}try{const r=await sf('https://ec.europa.eu/eurostat/web/main/news/euro-indicators?p_p_id=estatsearchportlet_WAR_estatsearchportlet_INSTANCE_OaTpFrwlabNK&p_p_lifecycle=2&p_p_state=normal&p_p_mode=view&p_p_resource_id=atom&p_p_cacheability=cacheLevelPage&_estatsearchportlet_WAR_estatsearchportlet_INSTANCE_OaTpFrwlabNK_pageNumber=1&_estatsearchportlet_WAR_estatsearchportlet_INSTANCE_OaTpFrwlabNK_pageSize=20&_estatsearchportlet_WAR_estatsearchportlet_INSTANCE_OaTpFrwlabNK_sort=lastUpdateDate&_estatsearchportlet_WAR_estatsearchportlet_INSTANCE_OaTpFrwlabNK_collection=CAT_PREREL');if(r&&r.ok){for(const e of ae(await r.text())){const pub=e.updated?td(e.updated):null;if(!pub||pub<cs)continue;const st=ss(e.title);if(st)items.push({bank:'ECB',source:'Eurostat',item_date:pub,title:e.title,url:e.link,is_statistical:true,hawk_pts:0,dove_pts:0,net_score:st.ns,label:st.lb,word_count:0,reasons:['numeric'],stat_metric:st.met,stat_value:st.val,stat_weight:st.w});else items.push({bank:'ECB',source:'Eurostat',item_date:pub,title:e.title,url:e.link,is_statistical:true,hawk_pts:0,dove_pts:0,net_score:0,label:'neutral',word_count:0,reasons:[],stat_metric:null,stat_value:null,stat_weight:0});}}}catch(e){console.error('Eurostat:',e);}return items;}
// Aggregation + DB
function ag(sub:It[]){if(!sub.length)return{avg:0,n:0,dist:{} as Record<string,number>,sentiment:'NEUTRAL'};const avg=Math.round(sub.reduce((s,i)=>s+i.net_score,0)/sub.length*1000)/1000;const sentiment=avg<=-0.5?'STRONGLY DOVISH':avg<-0.1?'DOVISH':avg>=0.5?'STRONGLY HAWKISH':avg>0.1?'HAWKISH':'NEUTRAL';const dist:Record<string,number>={};for(const i of sub)dist[i.label]=(dist[i.label]||0)+1;return{avg,n:sub.length,dist,sentiment};}
async function persist(bank:string,items:It[],s1:ReturnType<typeof ag>,s2:ReturnType<typeof ag>){const sbUrl=Deno.env.get('SUPABASE_URL')!;const sbKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const hd={'Authorization':'Bearer '+sbKey,'apikey':sbKey,'Content-Type':'application/json','Prefer':'resolution=merge-duplicates'};if(items.length){await fetch(sbUrl+'/rest/v1/sentiment_items',{method:'POST',headers:hd,body:JSON.stringify(items.map(i=>({bank:i.bank,source:i.source,item_date:i.item_date,title:i.title,url:i.url||'',is_statistical:i.is_statistical,hawk_pts:i.hawk_pts,dove_pts:i.dove_pts,net_score:i.net_score,label:i.label,word_count:i.word_count,reasons:i.reasons,stat_metric:i.stat_metric,stat_value:i.stat_value,stat_weight:i.stat_weight})))}).then(r=>r.text()).catch(e=>console.error('DB:',e));}await fetch(sbUrl+'/rest/v1/sentiment_scores',{method:'POST',headers:{...hd,'Prefer':'resolution=merge-duplicates'},body:JSON.stringify([{bank,score_1_avg:s1.avg,score_1_count:s1.n,score_1_label:s1.sentiment,score_1_dist:s1.dist,score_2_avg:s2.avg,score_2_count:s2.n,score_2_label:s2.sentiment,score_2_dist:s2.dist,fetched_at:new Date().toISOString()}])}).then(r=>r.text()).catch(e=>console.error('DB:',e));}
// Handler — POST only, no req.url access
Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { headers: CH });
  try {
    const body = req.method === 'POST' ? await req.json().catch(() => ({})) : {};
    const bank = body.bank || 'both';
    const days = body.days || 60;
    console.log('SA: bank=' + bank + ' days=' + days);
    const co = new Date(); co.setDate(co.getDate() - days); const cs = co.toISOString().split('T')[0];
    const fk = Deno.env.get('FRED_API_KEY') || '';
    const result: Record<string, any> = {};
    if (bank === 'both' || bank === 'FED') {
      const [fr, rs] = await Promise.allSettled([fk ? fetchFred(fk, days) : Promise.resolve([]), fetchRss(cs, 'FED')]);
      const fi: It[] = []; if (fr.status === 'fulfilled') fi.push(...fr.value); if (rs.status === 'fulfilled') fi.push(...rs.value);
      const s1 = ag(fi.filter(i => !i.is_statistical)), s2 = ag(fi);
      await persist('FED', fi, s1, s2); result.fed = { items: fi, score_1: s1, score_2: s2 }; console.log('Fed: ' + fi.length);
    }
    if (bank === 'both' || bank === 'ECB') {
      const [er, st] = await Promise.allSettled([fetchRss(cs, 'ECB'), fetchEcbStats(cs)]);
      const ei: It[] = []; if (er.status === 'fulfilled') ei.push(...er.value); if (st.status === 'fulfilled') ei.push(...st.value);
      const s1 = ag(ei.filter(i => !i.is_statistical)), s2 = ag(ei);
      await persist('ECB', ei, s1, s2); result.ecb = { items: ei, score_1: s1, score_2: s2 }; console.log('ECB: ' + ei.length);
    }
    return new Response(JSON.stringify(result), { headers: { ...CH, 'Content-Type': 'application/json' } });
  } catch (e) { console.error('Err:', e); return new Response(JSON.stringify({ error: e instanceof Error ? e.message : 'Unknown' }), { status: 500, headers: { ...CH, 'Content-Type': 'application/json' } }); }
});
